# Generated by Django 4.2.7 on 2023-12-03 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ('project', '0002_historicalproject_slug_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='invitation_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.NOTIFICATIONS_NOTIFICATION_MODEL),
        ),
    ]
