# Generated by Django 4.2.7 on 2023-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsection',
            name='state',
            field=models.CharField(choices=[(0, 'To do'), (1, 'In process'), (2, 'Ready for inspection'), (3, 'Done')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='state',
            field=models.CharField(choices=[(0, 'To do'), (1, 'In process'), (2, 'Ready for inspection'), (3, 'Done')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='state',
            field=models.CharField(choices=[(0, 'To do'), (1, 'In process'), (2, 'Ready for inspection'), (3, 'Done')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[(0, 'To do'), (1, 'In process'), (2, 'Ready for inspection'), (3, 'Done')], default=0, max_length=10),
        ),
        migrations.DeleteModel(
            name='SectionState',
        ),
        migrations.DeleteModel(
            name='TaskState',
        ),
    ]
