# Generated by Django 4.2.7 on 2023-12-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_sectionstate_taskstate_alter_historicalsection_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('slug', models.SlugField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('stype', models.PositiveIntegerField(choices=[(0, 'Started'), (1, 'Started'), (2, 'Inspect'), (3, 'Done')], db_index=True, default=0)),
            ],
            options={
                'ordering': ['stype', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.statemodel'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='task.statemodel'),
        ),
        migrations.AlterField(
            model_name='section',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.statemodel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.statemodel'),
        ),
        migrations.DeleteModel(
            name='SectionState',
        ),
        migrations.DeleteModel(
            name='TaskState',
        ),
    ]
