import BlogPost from "./BlogPost";
import "./ScalableApplicationSection.css";

const ScalableApplicationSection = () => {
  return (
    <div className="page-introduce-inner1">
      <div className="blog-post-parent">
        <BlogPost
          rectangle10="/rectangle-101@2x.png"
          howToBuildAScalableApplic="How to Build a Scalable Application up to 1 Million Users on AWS"
          seeMoreInformations="Read More"
          blogPostWidth="unset"
          blogPostHeight="unset"
          groupDivHeight="75px"
          howToBuildFontSize="16px"
          howToBuildFontWeight="500"
          howToBuildFontFamily="Inter"
          howToBuildWhiteSpace="unset"
          howToBuildTextAlign="left"
          linkClickDisplay="flex"
          linkClickFlexDirection="row"
          linkClickAlignItems="center"
          linkClickJustifyContent="flex-end"
          linkClickGap="15px"
          linkClickMargin="unset"
          seeMoreInformationsPosition="relative"
          seeMoreInformationsFontSize="16px"
          seeMoreInformationsLineHeight="25px"
          seeMoreInformationsFontWeight="500"
          seeMoreInformationsColor="#57007b"
          seeMoreInformationsTextAlign="left"
          seeMoreInformationsDisplay="inline-block"
          arrowRightLineIconPosition="relative"
          arrowRightLineIconWidth="24px"
          arrowRightLineIconHeight="24px"
          arrowRightLineIconOverflow="hidden"
          arrowRightLineIconFlexShrink="0"
        />
        <BlogPost
          howToBuildAScalableApplic="How to Build a Scalable Application up to 1 Million Users on AWS"
          rectangle10="/rectangle-102@2x.png"
          seeMoreInformations="   Tiện ích tích hợp"
          blogPostWidth="unset"
          blogPostHeight="unset"
          groupDivHeight="75px"
          howToBuildFontSize="unset"
          howToBuildFontWeight="unset"
          howToBuildFontFamily="unset"
          howToBuildWhiteSpace="pre-wrap"
          howToBuildTextAlign="left"
          linkClickDisplay="unset"
          linkClickFlexDirection="unset"
          linkClickAlignItems="unset"
          linkClickJustifyContent="unset"
          linkClickGap="unset"
          linkClickMargin="0"
          seeMoreInformationsPosition="unset"
          seeMoreInformationsFontSize="25px"
          seeMoreInformationsLineHeight="unset"
          seeMoreInformationsFontWeight="bold"
          seeMoreInformationsColor="unset"
          seeMoreInformationsTextAlign="unset"
          seeMoreInformationsDisplay="unset"
        />
        <BlogPost
          howToBuildAScalableApplic="How to Build a Scalable Application up to 1 Million Users on AWS"
          rectangle10="/rectangle-103@2x.png"
          seeMoreInformations="   Tự động hóa với   Butler  "
          blogPostWidth="unset"
          blogPostHeight="unset"
          groupDivHeight="75px"
          howToBuildFontSize="unset"
          howToBuildFontWeight="unset"
          howToBuildFontFamily="unset"
          howToBuildWhiteSpace="pre-wrap"
          howToBuildTextAlign="center"
          linkClickDisplay="unset"
          linkClickFlexDirection="unset"
          linkClickAlignItems="unset"
          linkClickJustifyContent="unset"
          linkClickGap="unset"
          linkClickMargin="0"
          seeMoreInformationsPosition="unset"
          seeMoreInformationsFontSize="25px"
          seeMoreInformationsLineHeight="unset"
          seeMoreInformationsFontWeight="bold"
          seeMoreInformationsColor="unset"
          seeMoreInformationsTextAlign="unset"
          seeMoreInformationsDisplay="unset"
        />
        <BlogPost
          howToBuildAScalableApplic="How to Build a Scalable Application up to 1 Million Users on AWS"
          rectangle10="/rectangle-104@2x.png"
          seeMoreInformations="Trello Enterprise"
          blogPostWidth="unset"
          blogPostHeight="unset"
          groupDivHeight="75px"
          howToBuildFontSize="unset"
          howToBuildFontWeight="unset"
          howToBuildFontFamily="unset"
          howToBuildWhiteSpace="unset"
          howToBuildTextAlign="left"
          linkClickDisplay="unset"
          linkClickFlexDirection="unset"
          linkClickAlignItems="unset"
          linkClickJustifyContent="unset"
          linkClickGap="unset"
          linkClickMargin="0"
          seeMoreInformationsPosition="unset"
          seeMoreInformationsFontSize="25px"
          seeMoreInformationsLineHeight="unset"
          seeMoreInformationsFontWeight="bold"
          seeMoreInformationsColor="unset"
          seeMoreInformationsTextAlign="unset"
          seeMoreInformationsDisplay="unset"
        />
        <BlogPost
          rectangle10="/rectangle-105@2x.png"
          howToBuildAScalableApplic="How to Build a Scalable Application up to 1 Million Users on AWS"
          seeMoreInformations="Read More"
          blogPostWidth="unset"
          blogPostHeight="unset"
          groupDivHeight="75px"
          howToBuildFontSize="16px"
          howToBuildFontWeight="500"
          howToBuildFontFamily="Inter"
          howToBuildWhiteSpace="unset"
          howToBuildTextAlign="left"
          linkClickDisplay="flex"
          linkClickFlexDirection="row"
          linkClickAlignItems="center"
          linkClickJustifyContent="flex-end"
          linkClickGap="15px"
          linkClickMargin="unset"
          seeMoreInformationsPosition="relative"
          seeMoreInformationsFontSize="16px"
          seeMoreInformationsLineHeight="25px"
          seeMoreInformationsFontWeight="500"
          seeMoreInformationsColor="#57007b"
          seeMoreInformationsTextAlign="left"
          seeMoreInformationsDisplay="inline-block"
          arrowRightLineIconPosition="relative"
          arrowRightLineIconWidth="24px"
          arrowRightLineIconHeight="24px"
          arrowRightLineIconOverflow="hidden"
          arrowRightLineIconFlexShrink="0"
        />
      </div>
    </div>
  );
};

export default ScalableApplicationSection;
